### ISSUE TITLE
Having the ability to delete a project once its completed

### ISSUE THREAD

**Issue by boudiccas** [Fuco1/org-clock-budget#1]
I've recently started using your excellent 'org-clock-budget' and have     just finished one project which was closed in my organiser file as     'DONE'. But is it possible from the [Clock budget] buffer to delete that     project please?

I see on line #369 this coding -

```
 (define-key map "s" 'org-clock-budget-report-sort)
 (define-key map "g" 'org-clock-budget-report)
 (define-key map "q" 'quit-window)
```

What I'm asking for is possibly "D" to delete that line from the [Clock     budget] buffer display, and for it not to show on any future displays?

**Comment by Fuco1** [comment]
Done, hit `D` anywhere on the line, it will remove the budget properties from the entry and refresh the budget report.

Thanks for the suggestion!
