### ISSUE TITLE
Tasks not showing up in report

### ISSUE THREAD

**Issue by gsingh93** [Fuco1/org-clock-budget#12]
When I run `org-clock-budget-report`, the report shows up with no tasks. I ran it in an org file that contained the following text:
```
* TODO Testing
:PROPERTIES:
:BUDGET_WEEK: 02:00
:END:
:LOGBOOK:
CLOCK: [2021-11-05 Fri 12:44]--[2021-11-05 Fri 12:46] =>  0:02
:END:
```

Am I configuring something incorrectly?

**Comment by Fuco1** [comment]
It works only on files belonging to the agenda.

**Comment by gsingh93** [comment]
Got it, thanks.
