### ISSUE TITLE
ceased to function since upgrade of dash

### ISSUE THREAD

**Issue by boudiccas** [Fuco1/org-clock-budget#3]
Since an upgrade of 'dash' on 2016-11-21 it seems that org-clock-budget has ceased to function, unfortunately. 

Is there any chance in which you could repair it please?

**Comment by Fuco1** [comment]
Do you have any error or some more information?

**Comment by boudiccas** [comment]
No, sorry. Just that its impossible now to update current reports, or to start new items in the report. Although they have new information, its not being passed over to teh budget report.

**Comment by boudiccas** [comment]
This turns out to have been a misconfiguration on my part, so this is what works -

*** TODO testpad
SCHEDULED: <2016-11-26 Sat +1d> DEADLINE: <2017-03-30 Thu>
:PROPERTIES:
:LAST_REPEAT: [2016-11-26 Sat 06:55]
:STYLE: habit
:REPEAT_TO_STATE: TODO
:BUDGET_WEEK: 35:00
:BUDGET_MONTH: 140:00
:BUDGET_YEAR: 500:00
:Effort: 500:00
:END:
:LOGBOOK:
_ - State "DONE" from "TODO" [2016-11-26 Sat 06:55]
:END:
:CLOCK:
CLOCK: [2016-11-25 Fri 14:33]--[2016-11-25 Fri 17:00] => 2:27
:END:

NB underscore added in :LOGBOOK: to stop it becoming a bulleted item
